# Generated by Django 2.2.2 on 2020-08-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='patient',
            new_name='patient_gpno',
        ),
    ]
