# Generated by Django 2.2.2 on 2020-08-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0002_auto_20200813_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
