# Generated by Django 2.2.2 on 2020-08-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0004_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
