# Generated by Django 2.2.2 on 2020-08-13 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0007_auto_20200813_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_with',
        ),
    ]
