# Generated by Django 2.2.2 on 2020-08-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0008_remove_appointment_appointment_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_with',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
