# Generated by Django 2.2.2 on 2020-08-14 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0010_auto_20200813_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_with',
            field=models.ForeignKey(blank=True, max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, to='myhealth.PatientProfile'),
        ),
    ]
