# Generated by Django 2.2.2 on 2020-08-14 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0011_auto_20200814_0241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
