# Generated by Django 2.2.2 on 2020-08-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0015_auto_20200814_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='date_posted',
            new_name='date_reply',
        ),
    ]
