# Generated by Django 2.2.2 on 2020-08-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0016_auto_20200814_1904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
