# Generated by Django 2.2.2 on 2020-08-14 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0021_question_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
    ]
