# Generated by Django 2.2.2 on 2020-08-15 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0022_remove_question_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
