# Generated by Django 2.2.2 on 2020-08-15 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0023_delete_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
