# Generated by Django 2.2.2 on 2020-08-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0025_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feature',
            field=models.BooleanField(default=False),
        ),
    ]
