# Generated by Django 2.2.2 on 2020-08-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0026_post_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='feature',
            new_name='featured',
        ),
    ]
