# Generated by Django 2.2.2 on 2020-08-16 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0034_auto_20200816_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ('date_created',)},
        ),
    ]
